stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:7.4-apache
      shellScript: |-
        apt-get update    
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-php:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml