stages:
- name: Build
  steps:
  - runScriptConfig:
      image: ubuntu:latest
      shellScript: |-
        
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-php:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
