apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-django
spec:
  selector:
    matchLabels:
      app: web-django
  replicas: 1
  template:
    metadata:
      labels:
        app: web-django
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: web-django
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8000
      restartPolicy: Always
     
---
apiVersion: v1
kind: Service
metadata:
  name: web-django
  labels:
    app: web-django
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30016
  selector:
    app: web-django
